# 公共配置文件
server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, point
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
        - id: add_request_header_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=point, 666
            - AddRequestParameter=name, dog
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback
#        - id: point-fallback
#          uri: https://github.com/point610
#          predicates:
#            - Path=/fallback
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-point-api-gateway
  protocol:
    name: dubbo
    port: 22223
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

