# 公共配置文件
server:
  port: 8090
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5000
      default-filters:
        - AddResponseHeader=source, point
      routes:
#        - id: api_route
#          uri: http://localhost:8123
#          predicates:
#            - Path=/api/**
        - id: add_request_header_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
          filters:
            - RequestHeaderSize=1000B
            - AddRequestHeader=point, 666
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-point-api-gateway
  protocol:
    name: dubbo
    port: 22223
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

